// Draft translation. Not loaded by the production console.
const plurals = new Intl.PluralRules("de-DE");
const unit = (count, one, other) => plurals.select(count) === "one" ? one : other;

export default {
  "eyebrow": "Privatsphäre von Grund auf",
  "heroTitle": "Dein Zuhause bleibt deins.",
  "heroLead": "Verbinde private KI und eigenen Familienspeicher, ohne dein Heimnetzwerk für das Internet zu öffnen.",
  "statusLabel": "Bridge-Status",
  "pairingStatus": "Verknüpfung",
  "aiStatusLabel": "Private KI",
  "storageStatusLabel": "Familienspeicher",
  "progressLabel": "Einrichtungsfortschritt",
  "stepCapabilities": "1 · Funktionen",
  "stepServices": "2 · Dienste",
  "stepPair": "3 · Verknüpfen",
  "stepReady": "4 · Bereit",
  "capabilitiesTitle": "Was soll dieser Bridge übernehmen?",
  "capabilitiesLead": "Wähle eine oder beide Funktionen. Du kannst das später ändern.",
  "useAi": "Meine private KI nutzen",
  "useAiLead": "Verarbeite unterstützte Ahova-Anfragen mit einem Modell bei dir zu Hause.",
  "useStorage": "Meinen Familienspeicher nutzen",
  "useStorageLead": "Bewahre Originaldateien der Familie in einem Ordner, auf einem NAS, WebDAV oder S3 auf.",
  "continue": "Weiter",
  "servicesTitle": "Deine Dienste verbinden",
  "servicesLead": "Bridge prüft alles, bevor er mit deiner Familie verknüpft wird.",
  "advanced": "Erweitert",
  "privateAi": "Private KI",
  "privateAiLead": "Wir können Ollama oder LM Studio finden, wenn sie auf diesem Computer laufen.",
  "aiType": "KI-Anwendung",
  "detectAuto": "Automatisch suchen",
  "model": "Modell",
  "findModelFirst": "Zuerst ein Modell suchen",
  "findAi": "Lokale KI suchen",
  "findAiHint": "Starte Ollama oder den LM-Studio-Server und wähle dann diese Schaltfläche.",
  "aiEndpoint": "Adresse der lokalen KI",
  "allowedModels": "Erlaubte Modelle",
  "familyStorage": "Familienspeicher",
  "familyStorageLead": "Wähle, wo Bridge neue Originaldateien der Familie speichern soll.",
  "storageType": "Speichertyp",
  "mountedOption": "Ordner auf diesem Computer oder NAS",
  "readOnly": "Nur lesen",
  "storageEndpoint": "Speicheradresse",
  "username": "Benutzername",
  "password": "Passwort oder App-Passwort",
  "keepPassword": "Leer lassen, um das gespeicherte Passwort zu behalten",
  "bucket": "Bucket",
  "prefix": "Ordnerpräfix",
  "accessKey": "Zugriffsschlüssel",
  "keepKey": "Leer lassen, um den gespeicherten Schlüssel zu behalten",
  "secretKey": "Geheimer Schlüssel",
  "keepSecret": "Leer lassen, um das gespeicherte Geheimnis zu behalten",
  "region": "Region",
  "mountedLead": "Bridge nutzt den bei der Installation gewählten Familienordner. Um einen anderen Ordner zu wählen, führe Folgendes im Installationsordner von Bridge aus:",
  "ahovaService": "Ahova-Dienst",
  "fileLimit": "Grenze für Dateiübertragung (Bytes)",
  "receiptRetention": "Aufbewahrung des Auftragsverlaufs (Tage)",
  "saveTest": "Speichern und prüfen",
  "continuePairing": "Weiter zur Verknüpfung",
  "back": "Zurück",
  "pairTitle": "Diesen Computer verknüpfen",
  "pairLead": "Öffne in Ahova <strong>Mehr → Dateien und Smart Actions → Ahova Bridge</strong>, erstelle einen Einmalcode und füge ihn hier ein.",
  "pairCode": "Einmaliger Verknüpfungscode",
  "pairButton": "Mit Ahova verknüpfen",
  "checkingBridge": "Dein Bridge wird geprüft…",
  "checkingLead": "Alle aktivierten Dienste müssen die Prüfung bestehen, bevor Ahova Aufträge hierher sendet.",
  "checkAgain": "Erneut prüfen",
  "changeSettings": "Einstellungen ändern",
  "diagnostics": "Bereinigte Diagnosedaten herunterladen",
  "manageTitle": "Diese Installation verwalten",
  "manageLead": "Hebe die Verknüpfung auf, bevor du diesen Bridge zu einer anderen Familie oder auf einen anderen Computer überträgst.",
  "unpair": "Verknüpfung dieses Computers aufheben",
  "footer": "Open-Source-Software unter MIT-Lizenz · nur ausgehende Verbindungen · Diagnose ohne Inhalte",
  "chooseCapability": "Wähle private KI, Familienspeicher oder beides.",
  "checking": "Wird geprüft…",
  "paired": "Verknüpft",
  "notPaired": "Nicht verknüpft",
  "ready": "Bereit",
  "off": "Aus",
  "attention": "Prüfung nötig",
  "readOnlyReady": "Bereit · nur lesen",
  "readWriteReady": "Bereit · lesen und schreiben",
  "finding": "Lokale KI wird gesucht…",
  "noAi": "Keine lokale KI gefunden. Starte Ollama oder den LM-Studio-Server und versuche es erneut.",
  "foundModels": n=>`${n} ${unit(n,"Modell gefunden","Modelle gefunden")}. Wähle unten eines aus.`,
  "foundNoModels": "Der KI-Server hat geantwortet, aber es wurden keine geladenen Modelle gefunden.",
  "configurationReady": "Deine Dienste sind bereit.",
  "configurationReadyLead": "Die aktivierten Dienste haben erfolgreich geantwortet. Fahre fort, um diesen Bridge zu verknüpfen.",
  "configurationAttention": "Ein Dienst muss geprüft werden.",
  "configurationAttentionLead": "Prüfe die Meldung oben oder öffne die erweiterten Einstellungen und teste erneut.",
  "saved": "Einstellungen gespeichert.",
  "pairingUnavailable": "Ahova konnte diesen Computer nicht verknüpfen. Prüfe den Code und die Internetverbindung.",
  "pairingRequired": "Gib den Einmalcode aus Ahova ein.",
  "configurationInvalid": "Prüfe die markierten Diensteinstellungen und versuche es erneut.",
  "requestFailed": "Bridge konnte diese Anfrage nicht abschließen. Versuche es erneut.",
  "pairedWith": name=>`Mit ${name} verknüpft.`,
  "readyTitle": "Dein Bridge ist bereit.",
  "readyLead": "Du kannst diese Seite schließen. Bridge läuft im Hintergrund weiter.",
  "needsTitle": "Ein paar Dinge müssen noch geprüft werden.",
  "needsLead": "Folge den Hinweisen unten und prüfe dann erneut.",
  "checkFailed": "Die Prüfung konnte nicht abgeschlossen werden.",
  "confirmUnpair": "Verknüpfung dieses Bridge aufheben? Ahova sendet dann keine Aufträge mehr an ihn.",
  "confirmLocal": "Ahova ist nicht erreichbar. Lokale Zugangsdaten trotzdem entfernen? Entziehe diesem Bridge den Zugriff in Ahova, sobald der Dienst wieder erreichbar ist.",
  "unpaired": "Bridge-Verknüpfung aufgehoben.",
  "downloadFailed": "Diagnosedaten konnten nicht erstellt werden. Versuche es erneut.",
  "language": "Sprache",
  "compatibleAi": "LM Studio / OpenAI-kompatibel",
  "checkControlHealthy": "Die Adresse des Ahova-Dienstes ist eingetragen.",
  "checkControlRequired": "Gib die Adresse des Ahova-Dienstes ein.",
  "checkControlAction": "Verwende die von Ahova angegebene Adresse.",
  "checkPairHealthy": "Bridge ist mit deiner Familie verbunden.",
  "checkPairRequired": "Bridge ist noch mit keiner Familie verbunden.",
  "checkPairAction": "Erstelle einen Einmalcode in Ahova und gib ihn im nächsten Schritt ein.",
  "checkAiHealthy": "Private KI antwortet.",
  "checkAiDisabled": "Private KI ist ausgeschaltet.",
  "checkAiUnavailable": "Private KI antwortet nicht.",
  "checkAiAction": "Starte den Modellserver und prüfe seine Adresse und das gewählte Modell.",
  "checkStorageHealthy": "Familienspeicher antwortet.",
  "checkStorageDisabled": "Familienspeicher ist ausgeschaltet.",
  "checkStorageUnavailable": "Familienspeicher antwortet nicht.",
  "checkStorageAction": "Prüfe den verbundenen Ordner oder die Speicheradresse, die Anmeldedaten und den Schreibzugriff.",
  "checkWorkerHealthy": "Bridge kann Anfragen von Ahova empfangen.",
  "checkWorkerUnavailable": "Bridge kann sich nicht mit Ahova verbinden.",
  "checkWorkerAction": "Prüfe die Verbindung und ob Bridge in Ahova noch Zugriff hat.",
  "checkWorkerChecking": "Warten auf die erste Verbindung.",
  "checkWorkerWaitAction": "Warte ein paar Sekunden und prüfe dann erneut.",
  "checkWorkerWaiting": "Bridge empfängt nach der Verknüpfung Anfragen.",
  "checkUnknown": "Diese Prüfung braucht Aufmerksamkeit.",
  "configRetention": "Wähle für den Auftragsverlauf eine Dauer zwischen 1 und 90 Tagen.",
  "configService": "Verwende für Ahova eine HTTPS-Adresse. HTTP ist nur für einen lokalen Testserver erlaubt.",
  "configAiAddress": "Gib die vollständige HTTP- oder HTTPS-Adresse deines KI-Servers ein.",
  "configFolder": "Wähle den vollständigen Pfad zum verbundenen Familienordner.",
  "configStorageAddress": "Gib die vollständige HTTP- oder HTTPS-Adresse des Speicherdienstes ein.",
  "configWebdav": "Gib deinen WebDAV-Benutzernamen und dein Passwort ein.",
  "configS3": "Gib den S3-Bucket-Namen, den Zugriffsschlüssel und den geheimen Schlüssel ein.",
  "configStorageType": "Wähle einen Ordner, WebDAV- oder S3-Speicher.",
  "configFileLimit": "Wähle eine Dateigrenze von 1 bis 5 MB.",
  "networkFailed": "Bridge ist nicht erreichbar. Prüfe, ob er läuft, und versuche es erneut.",
};
