// Draft translation. Not loaded by the production console.
const plurals = new Intl.PluralRules("es-ES");
const unit = (count, one, other) => plurals.select(count) === "one" ? one : other;

export default {
  "eyebrow": "Privado por diseño",
  "heroTitle": "Tu hogar sigue siendo tuyo.",
  "heroLead": "Conecta IA privada y almacenamiento propio de tu familia sin abrir la red de casa a internet.",
  "statusLabel": "Estado de Bridge",
  "pairingStatus": "Vinculación",
  "aiStatusLabel": "IA privada",
  "storageStatusLabel": "Almacenamiento familiar",
  "progressLabel": "Progreso de la configuración",
  "stepCapabilities": "1 · Funciones",
  "stepServices": "2 · Servicios",
  "stepPair": "3 · Vincular",
  "stepReady": "4 · Listo",
  "capabilitiesTitle": "¿Qué debe hacer este Bridge?",
  "capabilitiesLead": "Elige una opción o ambas. Puedes cambiarlo más adelante.",
  "useAi": "Usar mi IA privada",
  "useAiLead": "Procesa las solicitudes compatibles de Ahova con un modelo en tu casa.",
  "useStorage": "Usar mi almacenamiento familiar",
  "useStorageLead": "Guarda los originales familiares en una carpeta, NAS, WebDAV o S3.",
  "continue": "Continuar",
  "servicesTitle": "Conecta tus servicios",
  "servicesLead": "Bridge comprobará todo antes de vincularse con tu familia.",
  "advanced": "Avanzado",
  "privateAi": "IA privada",
  "privateAiLead": "Podemos encontrar Ollama o LM Studio si están en marcha en este equipo.",
  "aiType": "Aplicación de IA",
  "detectAuto": "Buscar automáticamente",
  "model": "Modelo",
  "findModelFirst": "Busca primero un modelo",
  "findAi": "Buscar IA local",
  "findAiHint": "Inicia Ollama o el servidor de LM Studio y luego pulsa este botón.",
  "aiEndpoint": "Dirección de la IA local",
  "allowedModels": "Modelos permitidos",
  "familyStorage": "Almacenamiento familiar",
  "familyStorageLead": "Elige dónde debe guardar Bridge los nuevos originales familiares.",
  "storageType": "Tipo de almacenamiento",
  "mountedOption": "Carpeta en este equipo o NAS",
  "readOnly": "Solo lectura",
  "storageEndpoint": "Dirección del almacenamiento",
  "username": "Nombre de usuario",
  "password": "Contraseña o contraseña de aplicación",
  "keepPassword": "Déjalo vacío para conservar la contraseña guardada",
  "bucket": "Bucket",
  "prefix": "Prefijo de carpeta",
  "accessKey": "Clave de acceso",
  "keepKey": "Déjalo vacío para conservar la clave guardada",
  "secretKey": "Clave secreta",
  "keepSecret": "Déjalo vacío para conservar el secreto guardado",
  "region": "Región",
  "mountedLead": "Bridge usa la carpeta familiar elegida durante la instalación. Para elegir otra, ejecuta esto desde la carpeta de instalación de Bridge:",
  "ahovaService": "Servicio de Ahova",
  "fileLimit": "Límite de transferencia de archivos (bytes)",
  "receiptRetention": "Conservación del historial de solicitudes (días)",
  "saveTest": "Guardar y probar",
  "continuePairing": "Continuar a la vinculación",
  "back": "Atrás",
  "pairTitle": "Vincula este equipo",
  "pairLead": "En Ahova, abre <strong>Más → Archivos y Smart Actions → Ahova Bridge</strong>, crea un código de un solo uso y pégalo aquí.",
  "pairCode": "Código de vinculación de un solo uso",
  "pairButton": "Vincular con Ahova",
  "checkingBridge": "Comprobando tu Bridge…",
  "checkingLead": "Todos los servicios activados deben superar la comprobación antes de que Ahova envíe solicitudes aquí.",
  "checkAgain": "Volver a comprobar",
  "changeSettings": "Cambiar ajustes",
  "diagnostics": "Descargar diagnóstico sin datos sensibles",
  "manageTitle": "Gestionar esta instalación",
  "manageLead": "Desvincula este Bridge antes de trasladarlo a otra familia o equipo.",
  "unpair": "Desvincular este equipo",
  "footer": "Software de código abierto con licencia MIT · solo conexiones salientes · diagnóstico sin contenido",
  "chooseCapability": "Elige IA privada, almacenamiento familiar o ambos.",
  "checking": "Comprobando…",
  "paired": "Vinculado",
  "notPaired": "Sin vincular",
  "ready": "Listo",
  "off": "Desactivado",
  "attention": "Necesita atención",
  "readOnlyReady": "Listo · solo lectura",
  "readWriteReady": "Listo · lectura y escritura",
  "finding": "Buscando IA local…",
  "noAi": "No se ha encontrado ninguna IA local. Inicia Ollama o el servidor de LM Studio e inténtalo de nuevo.",
  "foundModels": n=>`${n} ${unit(n,"modelo encontrado","modelos encontrados")}. Elige uno a continuación.`,
  "foundNoModels": "El servidor de IA ha respondido, pero no se han encontrado modelos cargados.",
  "configurationReady": "Tus servicios están listos.",
  "configurationReadyLead": "Los servicios activados han respondido correctamente. Continúa para vincular este Bridge.",
  "configurationAttention": "Hay un servicio que necesita atención.",
  "configurationAttentionLead": "Revisa el mensaje de arriba o abre los ajustes avanzados y vuelve a probar.",
  "saved": "Ajustes guardados.",
  "pairingUnavailable": "Ahova no ha podido vincular este equipo. Revisa el código y la conexión a internet.",
  "pairingRequired": "Introduce el código de un solo uso de Ahova.",
  "configurationInvalid": "Revisa los ajustes de servicio resaltados e inténtalo de nuevo.",
  "requestFailed": "Bridge no ha podido completar esa solicitud. Inténtalo de nuevo.",
  "pairedWith": name=>`Vinculado con ${name}.`,
  "readyTitle": "Tu Bridge está listo.",
  "readyLead": "Puedes cerrar esta página. Bridge seguirá funcionando en segundo plano.",
  "needsTitle": "Aún hay algunas cosas que revisar.",
  "needsLead": "Sigue las indicaciones de abajo y vuelve a comprobar.",
  "checkFailed": "No se ha podido completar la comprobación.",
  "confirmUnpair": "¿Desvincular este Bridge? Ahova dejará de enviarle solicitudes.",
  "confirmLocal": "Ahova no está disponible. ¿Eliminar de todos modos la credencial local? Revoca este Bridge en Ahova cuando el servicio vuelva a estar disponible.",
  "unpaired": "Bridge desvinculado.",
  "downloadFailed": "No se ha podido crear el diagnóstico. Inténtalo de nuevo.",
  "language": "Idioma",
  "compatibleAi": "LM Studio / compatible con OpenAI",
  "checkControlHealthy": "La dirección del servicio de Ahova está configurada.",
  "checkControlRequired": "Introduce la dirección del servicio de Ahova.",
  "checkControlAction": "Usa la dirección proporcionada por Ahova.",
  "checkPairHealthy": "Bridge está conectado a tu familia.",
  "checkPairRequired": "Bridge aún no está conectado a una familia.",
  "checkPairAction": "Crea un código de un solo uso en Ahova e introdúcelo en el siguiente paso.",
  "checkAiHealthy": "La IA privada responde.",
  "checkAiDisabled": "La IA privada está desactivada.",
  "checkAiUnavailable": "La IA privada no responde.",
  "checkAiAction": "Inicia el servidor del modelo y revisa su dirección y el modelo seleccionado.",
  "checkStorageHealthy": "El almacenamiento familiar responde.",
  "checkStorageDisabled": "El almacenamiento familiar está desactivado.",
  "checkStorageUnavailable": "El almacenamiento familiar no responde.",
  "checkStorageAction": "Revisa la carpeta conectada o la dirección del almacenamiento, los datos de acceso y los permisos de escritura.",
  "checkWorkerHealthy": "Bridge puede recibir solicitudes de Ahova.",
  "checkWorkerUnavailable": "Bridge no puede conectarse a Ahova.",
  "checkWorkerAction": "Revisa la conexión y comprueba si Bridge sigue teniendo acceso en Ahova.",
  "checkWorkerChecking": "Esperando la primera conexión.",
  "checkWorkerWaitAction": "Espera unos segundos y vuelve a comprobar.",
  "checkWorkerWaiting": "Bridge empezará a recibir solicitudes después de la vinculación.",
  "checkUnknown": "Esta comprobación necesita atención.",
  "configRetention": "Elige entre 1 y 90 días para el historial de solicitudes.",
  "configService": "Usa una dirección HTTPS para Ahova. HTTP solo está permitido para un servidor de prueba local.",
  "configAiAddress": "Introduce la dirección HTTP o HTTPS completa de tu servidor de IA.",
  "configFolder": "Elige la ruta completa de la carpeta familiar conectada.",
  "configStorageAddress": "Introduce la dirección HTTP o HTTPS completa del servicio de almacenamiento.",
  "configWebdav": "Introduce tu nombre de usuario y contraseña de WebDAV.",
  "configS3": "Introduce el nombre del bucket S3, la clave de acceso y la clave secreta.",
  "configStorageType": "Elige una carpeta, almacenamiento WebDAV o S3.",
  "configFileLimit": "Elige un límite de archivo de 1 a 5 MB.",
  "networkFailed": "No se ha podido acceder a Bridge. Comprueba que esté en marcha e inténtalo de nuevo.",
};
