// Draft translation. Not loaded by the production console.
const plurals = new Intl.PluralRules("fr-FR");
const unit = (count, one, other) => plurals.select(count) === "one" ? one : other;

export default {
  "eyebrow": "Privé par conception",
  "heroTitle": "Ton foyer reste le tien.",
  "heroLead": "Connecte une IA privée et un stockage familial sans ouvrir ton réseau domestique à Internet.",
  "statusLabel": "État de Bridge",
  "pairingStatus": "Association",
  "aiStatusLabel": "IA privée",
  "storageStatusLabel": "Stockage familial",
  "progressLabel": "Progression de la configuration",
  "stepCapabilities": "1 · Fonctions",
  "stepServices": "2 · Services",
  "stepPair": "3 · Associer",
  "stepReady": "4 · Prêt",
  "capabilitiesTitle": "Que doit faire ce Bridge ?",
  "capabilitiesLead": "Choisis une option ou les deux. Tu pourras modifier ce choix plus tard.",
  "useAi": "Utiliser mon IA privée",
  "useAiLead": "Traite les demandes Ahova compatibles avec un modèle chez toi.",
  "useStorage": "Utiliser mon stockage familial",
  "useStorageLead": "Conserve les originaux de la famille dans un dossier, un NAS, WebDAV ou S3.",
  "continue": "Continuer",
  "servicesTitle": "Connecte tes services",
  "servicesLead": "Bridge vérifie tout avant de s’associer à ta famille.",
  "advanced": "Avancé",
  "privateAi": "IA privée",
  "privateAiLead": "Nous pouvons trouver Ollama ou LM Studio s’ils fonctionnent sur cet ordinateur.",
  "aiType": "Application d’IA",
  "detectAuto": "Rechercher automatiquement",
  "model": "Modèle",
  "findModelFirst": "Trouve d’abord un modèle",
  "findAi": "Rechercher l’IA locale",
  "findAiHint": "Lance Ollama ou le serveur LM Studio, puis sélectionne ce bouton.",
  "aiEndpoint": "Adresse de l’IA locale",
  "allowedModels": "Modèles autorisés",
  "familyStorage": "Stockage familial",
  "familyStorageLead": "Choisis où Bridge doit conserver les nouveaux originaux de la famille.",
  "storageType": "Type de stockage",
  "mountedOption": "Dossier sur cet ordinateur ou NAS",
  "readOnly": "Lecture seule",
  "storageEndpoint": "Adresse du stockage",
  "username": "Nom d’utilisateur",
  "password": "Mot de passe ou mot de passe d’application",
  "keepPassword": "Laisse vide pour conserver le mot de passe enregistré",
  "bucket": "Bucket",
  "prefix": "Préfixe de dossier",
  "accessKey": "Clé d’accès",
  "keepKey": "Laisse vide pour conserver la clé enregistrée",
  "secretKey": "Clé secrète",
  "keepSecret": "Laisse vide pour conserver le secret enregistré",
  "region": "Région",
  "mountedLead": "Bridge utilise le dossier familial choisi à l’installation. Pour en choisir un autre, exécute ceci depuis le dossier d’installation de Bridge :",
  "ahovaService": "Service Ahova",
  "fileLimit": "Limite de transfert de fichiers (octets)",
  "receiptRetention": "Conservation de l’historique des demandes (jours)",
  "saveTest": "Enregistrer et tester",
  "continuePairing": "Continuer vers l’association",
  "back": "Retour",
  "pairTitle": "Associe cet ordinateur",
  "pairLead": "Dans Ahova, ouvre <strong>Plus → Fichiers et Smart Actions → Ahova Bridge</strong>, crée un code à usage unique et colle-le ici.",
  "pairCode": "Code d’association à usage unique",
  "pairButton": "Associer à Ahova",
  "checkingBridge": "Vérification de ton Bridge…",
  "checkingLead": "Chaque service activé doit réussir la vérification avant qu’Ahova n’envoie des demandes ici.",
  "checkAgain": "Vérifier à nouveau",
  "changeSettings": "Modifier les paramètres",
  "diagnostics": "Télécharger le diagnostic sans données sensibles",
  "manageTitle": "Gérer cette installation",
  "manageLead": "Dissocie ce Bridge avant de le transférer vers une autre famille ou un autre ordinateur.",
  "unpair": "Dissocier cet ordinateur",
  "footer": "Logiciel open source sous licence MIT · connexions sortantes uniquement · diagnostic sans contenu",
  "chooseCapability": "Choisis l’IA privée, le stockage familial ou les deux.",
  "checking": "Vérification…",
  "paired": "Associé",
  "notPaired": "Non associé",
  "ready": "Prêt",
  "off": "Désactivé",
  "attention": "À vérifier",
  "readOnlyReady": "Prêt · lecture seule",
  "readWriteReady": "Prêt · lecture et écriture",
  "finding": "Recherche de l’IA locale…",
  "noAi": "Aucune IA locale trouvée. Lance Ollama ou le serveur LM Studio et réessaie.",
  "foundModels": n=>`${n} ${unit(n,"modèle trouvé","modèles trouvés")}. Choisis-en un ci-dessous.`,
  "foundNoModels": "Le serveur d’IA a répondu, mais aucun modèle chargé n’a été trouvé.",
  "configurationReady": "Tes services sont prêts.",
  "configurationReadyLead": "Les services activés ont répondu correctement. Continue pour associer ce Bridge.",
  "configurationAttention": "Un service doit être vérifié.",
  "configurationAttentionLead": "Lis le message ci-dessus ou ouvre les paramètres avancés, puis relance le test.",
  "saved": "Paramètres enregistrés.",
  "pairingUnavailable": "Ahova n’a pas pu associer cet ordinateur. Vérifie le code et la connexion Internet.",
  "pairingRequired": "Saisis le code à usage unique d’Ahova.",
  "configurationInvalid": "Vérifie les paramètres de service signalés et réessaie.",
  "requestFailed": "Bridge n’a pas pu terminer cette demande. Réessaie.",
  "pairedWith": name=>`Associé à ${name}.`,
  "readyTitle": "Ton Bridge est prêt.",
  "readyLead": "Tu peux fermer cette page. Bridge continue de fonctionner en arrière-plan.",
  "needsTitle": "Quelques points restent à vérifier.",
  "needsLead": "Suis les indications ci-dessous, puis vérifie à nouveau.",
  "checkFailed": "Impossible de terminer la vérification.",
  "confirmUnpair": "Dissocier ce Bridge ? Ahova cessera de lui envoyer des demandes.",
  "confirmLocal": "Ahova est inaccessible. Supprimer quand même l’identifiant local ? Révoque ce Bridge dans Ahova quand le service sera de nouveau disponible.",
  "unpaired": "Bridge dissocié.",
  "downloadFailed": "Impossible de créer le diagnostic. Réessaie.",
  "language": "Langue",
  "compatibleAi": "LM Studio / compatible OpenAI",
  "checkControlHealthy": "L’adresse du service Ahova est définie.",
  "checkControlRequired": "Saisis l’adresse du service Ahova.",
  "checkControlAction": "Utilise l’adresse fournie par Ahova.",
  "checkPairHealthy": "Bridge est connecté à ta famille.",
  "checkPairRequired": "Bridge n’est pas encore connecté à une famille.",
  "checkPairAction": "Crée un code à usage unique dans Ahova et saisis-le à l’étape suivante.",
  "checkAiHealthy": "L’IA privée répond.",
  "checkAiDisabled": "L’IA privée est désactivée.",
  "checkAiUnavailable": "L’IA privée ne répond pas.",
  "checkAiAction": "Lance le serveur de modèles et vérifie son adresse ainsi que le modèle choisi.",
  "checkStorageHealthy": "Le stockage familial répond.",
  "checkStorageDisabled": "Le stockage familial est désactivé.",
  "checkStorageUnavailable": "Le stockage familial ne répond pas.",
  "checkStorageAction": "Vérifie le dossier connecté ou l’adresse du stockage, les identifiants et l’accès en écriture.",
  "checkWorkerHealthy": "Bridge peut recevoir des demandes d’Ahova.",
  "checkWorkerUnavailable": "Bridge ne peut pas se connecter à Ahova.",
  "checkWorkerAction": "Vérifie la connexion et si Bridge dispose toujours d’un accès dans Ahova.",
  "checkWorkerChecking": "En attente de la première connexion.",
  "checkWorkerWaitAction": "Attends quelques secondes, puis vérifie à nouveau.",
  "checkWorkerWaiting": "Bridge commencera à recevoir des demandes après l’association.",
  "checkUnknown": "Cette vérification nécessite ton attention.",
  "configRetention": "Choisis entre 1 et 90 jours pour l’historique des demandes.",
  "configService": "Utilise une adresse HTTPS pour Ahova. HTTP n’est autorisé que pour un serveur de test local.",
  "configAiAddress": "Saisis l’adresse HTTP ou HTTPS complète de ton serveur d’IA.",
  "configFolder": "Choisis le chemin complet du dossier familial connecté.",
  "configStorageAddress": "Saisis l’adresse HTTP ou HTTPS complète du service de stockage.",
  "configWebdav": "Saisis ton nom d’utilisateur et ton mot de passe WebDAV.",
  "configS3": "Saisis le nom du bucket S3, la clé d’accès et la clé secrète.",
  "configStorageType": "Choisis un dossier, un stockage WebDAV ou S3.",
  "configFileLimit": "Choisis une limite de fichier de 1 à 5 Mo.",
  "networkFailed": "Impossible de joindre Bridge. Vérifie qu’il fonctionne et réessaie.",
};
