// Draft translation. Not loaded by the production console.
const plurals = new Intl.PluralRules("pt-PT");
const unit = (count, one, other) => plurals.select(count) === "one" ? one : other;

export default {
  "eyebrow": "Privado por conceção",
  "heroTitle": "A tua casa continua a ser tua.",
  "heroLead": "Liga a IA privada e o armazenamento da tua família sem abrir a rede de casa à internet.",
  "statusLabel": "Estado do Bridge",
  "pairingStatus": "Associação",
  "aiStatusLabel": "IA privada",
  "storageStatusLabel": "Armazenamento da família",
  "progressLabel": "Progresso da configuração",
  "stepCapabilities": "1 · Funcionalidades",
  "stepServices": "2 · Serviços",
  "stepPair": "3 · Associar",
  "stepReady": "4 · Pronto",
  "capabilitiesTitle": "O que deve fazer este Bridge?",
  "capabilitiesLead": "Escolhe uma opção ou ambas. Podes alterar isto mais tarde.",
  "useAi": "Usar a minha IA privada",
  "useAiLead": "Processa os pedidos suportados da Ahova com um modelo em tua casa.",
  "useStorage": "Usar o armazenamento da minha família",
  "useStorageLead": "Guarda os originais da família numa pasta, NAS, WebDAV ou S3.",
  "continue": "Continuar",
  "servicesTitle": "Liga os teus serviços",
  "servicesLead": "O Bridge verifica tudo antes de se associar à tua família.",
  "advanced": "Avançado",
  "privateAi": "IA privada",
  "privateAiLead": "Podemos encontrar o Ollama ou o LM Studio se estiverem a funcionar neste computador.",
  "aiType": "Aplicação de IA",
  "detectAuto": "Procurar automaticamente",
  "model": "Modelo",
  "findModelFirst": "Procura primeiro um modelo",
  "findAi": "Procurar IA local",
  "findAiHint": "Inicia o Ollama ou o servidor do LM Studio e depois seleciona este botão.",
  "aiEndpoint": "Endereço da IA local",
  "allowedModels": "Modelos permitidos",
  "familyStorage": "Armazenamento da família",
  "familyStorageLead": "Escolhe onde o Bridge deve guardar os novos originais da família.",
  "storageType": "Tipo de armazenamento",
  "mountedOption": "Pasta neste computador ou NAS",
  "readOnly": "Só de leitura",
  "storageEndpoint": "Endereço do armazenamento",
  "username": "Nome de utilizador",
  "password": "Palavra-passe ou palavra-passe de aplicação",
  "keepPassword": "Deixa em branco para manter a palavra-passe guardada",
  "bucket": "Bucket",
  "prefix": "Prefixo da pasta",
  "accessKey": "Chave de acesso",
  "keepKey": "Deixa em branco para manter a chave guardada",
  "secretKey": "Chave secreta",
  "keepSecret": "Deixa em branco para manter o segredo guardado",
  "region": "Região",
  "mountedLead": "O Bridge usa a pasta da família escolhida durante a instalação. Para escolher outra pasta, executa isto a partir da pasta de instalação do Bridge:",
  "ahovaService": "Serviço da Ahova",
  "fileLimit": "Limite de transferência de ficheiros (bytes)",
  "receiptRetention": "Retenção do histórico de pedidos (dias)",
  "saveTest": "Guardar e testar",
  "continuePairing": "Continuar para a associação",
  "back": "Voltar",
  "pairTitle": "Associa este computador",
  "pairLead": "Na Ahova, abre <strong>Mais → Ficheiros e Smart Actions → Ahova Bridge</strong>, cria um código de utilização única e cola-o aqui.",
  "pairCode": "Código de associação de utilização única",
  "pairButton": "Associar à Ahova",
  "checkingBridge": "A verificar o teu Bridge…",
  "checkingLead": "Todos os serviços ativos têm de passar a verificação antes de a Ahova enviar pedidos para aqui.",
  "checkAgain": "Verificar novamente",
  "changeSettings": "Alterar definições",
  "diagnostics": "Descarregar diagnóstico sem dados sensíveis",
  "manageTitle": "Gerir esta instalação",
  "manageLead": "Desassocia este Bridge antes de o transferires para outra família ou computador.",
  "unpair": "Desassociar este computador",
  "footer": "Software de código aberto com licença MIT · apenas ligações de saída · diagnóstico sem conteúdo",
  "chooseCapability": "Escolhe IA privada, armazenamento da família ou ambos.",
  "checking": "A verificar…",
  "paired": "Associado",
  "notPaired": "Não associado",
  "ready": "Pronto",
  "off": "Desativado",
  "attention": "Precisa de atenção",
  "readOnlyReady": "Pronto · só de leitura",
  "readWriteReady": "Pronto · leitura e escrita",
  "finding": "A procurar IA local…",
  "noAi": "Não foi encontrada IA local. Inicia o Ollama ou o servidor do LM Studio e tenta novamente.",
  "foundModels": n=>`${n} ${unit(n,"modelo encontrado","modelos encontrados")}. Escolhe um abaixo.`,
  "foundNoModels": "O servidor de IA respondeu, mas não foram encontrados modelos carregados.",
  "configurationReady": "Os teus serviços estão prontos.",
  "configurationReadyLead": "Os serviços ativos responderam corretamente. Continua para associar este Bridge.",
  "configurationAttention": "Um serviço precisa de atenção.",
  "configurationAttentionLead": "Revê a mensagem acima ou abre as definições avançadas e testa novamente.",
  "saved": "Definições guardadas.",
  "pairingUnavailable": "A Ahova não conseguiu associar este computador. Verifica o código e a ligação à internet.",
  "pairingRequired": "Introduz o código de utilização única da Ahova.",
  "configurationInvalid": "Revê as definições do serviço assinaladas e tenta novamente.",
  "requestFailed": "O Bridge não conseguiu concluir esse pedido. Tenta novamente.",
  "pairedWith": name=>`Associado a ${name}.`,
  "readyTitle": "O teu Bridge está pronto.",
  "readyLead": "Podes fechar esta página. O Bridge continuará a funcionar em segundo plano.",
  "needsTitle": "Ainda há algumas coisas a verificar.",
  "needsLead": "Segue as indicações abaixo e verifica novamente.",
  "checkFailed": "Não foi possível concluir a verificação.",
  "confirmUnpair": "Desassociar este Bridge? A Ahova deixará de lhe enviar pedidos.",
  "confirmLocal": "A Ahova está inacessível. Remover a credencial local mesmo assim? Revoga este Bridge na Ahova quando o serviço voltar a estar disponível.",
  "unpaired": "Bridge desassociado.",
  "downloadFailed": "Não foi possível criar o diagnóstico. Tenta novamente.",
  "language": "Idioma",
  "compatibleAi": "LM Studio / compatível com OpenAI",
  "checkControlHealthy": "O endereço do serviço da Ahova está definido.",
  "checkControlRequired": "Introduz o endereço do serviço da Ahova.",
  "checkControlAction": "Usa o endereço fornecido pela Ahova.",
  "checkPairHealthy": "O Bridge está ligado à tua família.",
  "checkPairRequired": "O Bridge ainda não está ligado a uma família.",
  "checkPairAction": "Cria um código de utilização única na Ahova e introduz o código no próximo passo.",
  "checkAiHealthy": "A IA privada está a responder.",
  "checkAiDisabled": "A IA privada está desativada.",
  "checkAiUnavailable": "A IA privada não responde.",
  "checkAiAction": "Inicia o servidor do modelo e verifica o endereço e o modelo selecionado.",
  "checkStorageHealthy": "O armazenamento da família está a responder.",
  "checkStorageDisabled": "O armazenamento da família está desativado.",
  "checkStorageUnavailable": "O armazenamento da família não responde.",
  "checkStorageAction": "Verifica a pasta ligada ou o endereço do armazenamento, os dados de início de sessão e as permissões de escrita.",
  "checkWorkerHealthy": "O Bridge pode receber pedidos da Ahova.",
  "checkWorkerUnavailable": "O Bridge não consegue ligar-se à Ahova.",
  "checkWorkerAction": "Verifica a ligação e se o Bridge ainda tem acesso na Ahova.",
  "checkWorkerChecking": "À espera da primeira ligação.",
  "checkWorkerWaitAction": "Espera alguns segundos e verifica novamente.",
  "checkWorkerWaiting": "O Bridge começará a receber pedidos depois da associação.",
  "checkUnknown": "Esta verificação precisa de atenção.",
  "configRetention": "Escolhe entre 1 e 90 dias para o histórico de pedidos.",
  "configService": "Usa um endereço HTTPS para a Ahova. HTTP só é permitido num servidor de teste local.",
  "configAiAddress": "Introduz o endereço HTTP ou HTTPS completo do teu servidor de IA.",
  "configFolder": "Escolhe o caminho completo para a pasta da família ligada.",
  "configStorageAddress": "Introduz o endereço HTTP ou HTTPS completo do serviço de armazenamento.",
  "configWebdav": "Introduz o teu nome de utilizador e palavra-passe do WebDAV.",
  "configS3": "Introduz o nome do bucket S3, a chave de acesso e a chave secreta.",
  "configStorageType": "Escolhe uma pasta, armazenamento WebDAV ou S3.",
  "configFileLimit": "Escolhe um limite de ficheiro entre 1 e 5 MB.",
  "networkFailed": "Não foi possível contactar o Bridge. Verifica se está a funcionar e tenta novamente.",
};
