// Draft only. Native-speaker review and runtime integration are pending.
// Source: src/Ahova.Bridge/wwwroot/index.html
export default {
  "eyebrow": "从架构上保护隐私",
  "heroTitle": "你的家，始终由你掌控。",
  "heroLead": "连接私有 AI 和家庭自有存储，无需向外网开放家庭网络。",
  "statusLabel": "Bridge 状态",
  "pairingStatus": "配对",
  "aiStatusLabel": "私有 AI",
  "storageStatusLabel": "家庭存储",
  "progressLabel": "设置进度",
  "stepCapabilities": "1 · 功能",
  "stepServices": "2 · 服务",
  "stepPair": "3 · 配对",
  "stepReady": "4 · 就绪",
  "capabilitiesTitle": "希望此 Bridge 提供哪些功能？",
  "capabilitiesLead": "可选一项或两项，之后仍可修改。",
  "useAi": "使用我的私有 AI",
  "useAiLead": "用家中的模型处理受支持的 Ahova 请求。",
  "useStorage": "使用我的家庭存储",
  "useStorageLead": "将家庭原件保存在文件夹、NAS、WebDAV 或 S3 中。",
  "continue": "继续",
  "servicesTitle": "连接你的服务",
  "servicesLead": "与家庭配对前，Bridge 会先检查各项服务。",
  "advanced": "高级设置",
  "privateAi": "私有 AI",
  "privateAiLead": "可查找此电脑上运行的 Ollama 或 LM Studio。",
  "aiType": "AI 应用",
  "detectAuto": "自动查找",
  "model": "模型",
  "findModelFirst": "请先查找模型",
  "findAi": "查找本地 AI",
  "findAiHint": "启动 Ollama 或 LM Studio 服务器，然后点击此按钮。",
  "aiEndpoint": "本地 AI 服务地址",
  "allowedModels": "允许使用的模型",
  "familyStorage": "家庭存储",
  "familyStorageLead": "选择 Bridge 保存新家庭原件的位置。",
  "storageType": "存储类型",
  "mountedOption": "本机或 NAS 上的文件夹",
  "readOnly": "只读",
  "storageEndpoint": "存储服务地址",
  "username": "用户名",
  "password": "密码或应用专用密码",
  "keepPassword": "留空以保留已保存的密码",
  "bucket": "存储桶",
  "prefix": "文件夹前缀",
  "accessKey": "访问密钥",
  "keepKey": "留空以保留已保存的访问密钥",
  "secretKey": "秘密访问密钥",
  "keepSecret": "留空以保留已保存的秘密访问密钥",
  "region": "区域",
  "mountedLead": "Bridge 使用安装时选定的家庭文件夹。如需更换，请在 Bridge 安装文件夹中运行：",
  "ahovaService": "Ahova 服务",
  "fileLimit": "文件传输上限（字节）",
  "receiptRetention": "处理记录保留时间（天）",
  "saveTest": "保存并测试",
  "continuePairing": "继续配对",
  "back": "返回",
  "pairTitle": "配对此电脑",
  "pairLead": "在 Ahova 中打开<strong>更多 → 文件与 Smart Actions → Ahova Bridge</strong>，生成一次性配对码并粘贴到这里。",
  "pairCode": "一次性配对码",
  "pairButton": "与 Ahova 配对",
  "checkingBridge": "正在检查 Bridge…",
  "checkingLead": "所有已启用服务通过检查后，Ahova 才会向此处发送请求。",
  "checkAgain": "再次检查",
  "changeSettings": "修改设置",
  "diagnostics": "下载已隐去敏感内容的诊断包",
  "manageTitle": "管理此安装",
  "manageLead": "将此 Bridge 转移到其他家庭或电脑前，请先解除配对。",
  "unpair": "解除此电脑的配对",
  "footer": "MIT 许可开源软件 · 仅主动向外连接 · 诊断隐去敏感内容",
  "chooseCapability": "请选择私有 AI、家庭存储，或同时选择两项。",
  "checking": "检查中…",
  "paired": "已配对",
  "notPaired": "未配对",
  "ready": "就绪",
  "off": "已关闭",
  "attention": "需要处理",
  "readOnlyReady": "就绪 · 只读",
  "readWriteReady": "就绪 · 可读写",
  "finding": "正在查找本地 AI…",
  "noAi": "未找到本地 AI。请启动 Ollama 或 LM Studio 服务器后重试。",
  "foundModels": n => `找到 ${n} 个模型，请在下方选择。`,
  "foundNoModels": "AI 服务器已响应，但未找到已加载的模型。",
  "configurationReady": "服务已就绪。",
  "configurationReadyLead": "已启用服务均已成功响应，可继续配对此 Bridge。",
  "configurationAttention": "一项服务需要处理。",
  "configurationAttentionLead": "请查看上方提示或打开高级设置，然后再次测试。",
  "saved": "设置已保存。",
  "pairingUnavailable": "Ahova 无法与此电脑配对。请检查配对码和网络连接。",
  "pairingRequired": "请输入 Ahova 生成的一次性配对码。",
  "configurationInvalid": "请检查标出的服务设置后重试。",
  "requestFailed": "Bridge 无法完成此请求，请重试。",
  "pairedWith": name => `已与 ${name} 配对。`,
  "readyTitle": "Bridge 已就绪。",
  "readyLead": "你可以关闭此页面，Bridge 会继续在后台运行。",
  "needsTitle": "还有几项内容需要处理。",
  "needsLead": "请按下方提示操作，然后再次检查。",
  "checkFailed": "无法完成检查。",
  "confirmUnpair": "解除此 Bridge 的配对？Ahova 将停止向它发送请求。",
  "confirmLocal": "无法连接 Ahova。仍要移除本地凭据吗？服务恢复后，请在 Ahova 中撤销此 Bridge。",
  "unpaired": "Bridge 已解除配对。",
  "downloadFailed": "无法生成诊断包，请重试。",
  "language": "语言",
  "compatibleAi": "LM Studio／兼容 OpenAI 的服务",
  "checkControlHealthy": "Ahova 服务地址已设置。",
  "checkControlRequired": "请输入 Ahova 服务地址。",
  "checkControlAction": "请使用 Ahova 提供的地址。",
  "checkPairHealthy": "Bridge 已连接到你的家庭。",
  "checkPairRequired": "Bridge 尚未连接到家庭。",
  "checkPairAction": "请在 Ahova 中生成一次性配对码，并在下一步输入。",
  "checkAiHealthy": "私有 AI 正常响应。",
  "checkAiDisabled": "私有 AI 已关闭。",
  "checkAiUnavailable": "私有 AI 未响应。",
  "checkAiAction": "请启动模型服务器，并检查地址和所选模型。",
  "checkStorageHealthy": "家庭存储正常响应。",
  "checkStorageDisabled": "家庭存储已关闭。",
  "checkStorageUnavailable": "家庭存储未响应。",
  "checkStorageAction": "请检查连接的文件夹或存储地址、登录信息和写入权限。",
  "checkWorkerHealthy": "Bridge 可以接收 Ahova 请求。",
  "checkWorkerUnavailable": "Bridge 无法连接 Ahova。",
  "checkWorkerAction": "请检查网络连接，以及 Bridge 在 Ahova 中是否仍有访问权限。",
  "checkWorkerChecking": "等待首次连接。",
  "checkWorkerWaitAction": "请等待几秒后再次检查。",
  "checkWorkerWaiting": "配对后，Bridge 将开始接收请求。",
  "checkUnknown": "此检查项目需要处理。",
  "configRetention": "处理记录保留时间请选择 1 至 90 天。",
  "configService": "Ahova 须使用 HTTPS 地址。只有本地测试服务器允许使用 HTTP。",
  "configAiAddress": "请输入 AI 服务器完整的 HTTP 或 HTTPS 地址。",
  "configFolder": "请选择已连接家庭文件夹的完整路径。",
  "configStorageAddress": "请输入存储服务完整的 HTTP 或 HTTPS 地址。",
  "configWebdav": "请输入 WebDAV 用户名和密码。",
  "configS3": "请输入 S3 存储桶名称、访问密钥和秘密访问密钥。",
  "configStorageType": "请选择文件夹、WebDAV 或 S3 存储。",
  "configFileLimit": "请选择 1 至 5 MB 的文件上限。",
  "networkFailed": "无法连接 Bridge。请确认它正在运行后重试。"
};
